# Generated by Django 4.1.13 on 2024-01-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
